qualificationRequire = [
    { key: "ISO9001", value: "ISO9001质量体系认证" },
    { key: "ISO14001", value: "ISO14001环境管理质量体系认证" },
    { key: "ZYAQGLTX", value: "职业健康安全管理体系认证" },
    { key: "ISO/TS16949", value: "ISO/TS16949汽车工业管理体系认证" },
    { key: "ISO14020", value: "ISO14020环境标志技术标准认证" },
    { key: "SA 8000", value: "SA 8000社会责任管理体系认证" },
    { key: "IECQ QC080000", value: "IECQ QC080000电子电气元件和产品危害物质减免标准和要求" },
    { key: "YY/T0287", value: "YY/T0287医疗器械质量管理体系认证" },
    { key: "ISO13485", value: "ISO13485医疗器械质量管理体系认证" },
    { key: "ISO/IEC27001", value: "ISO/IEC27001信息安全管理体系认证" },
    { key: "ISO/ISO22000", value: "ISO/ISO22000食品安全管理体系认证" },
    { key: "ISO10012", value: "ISO10012测量管理体系认证" },
    { key: "WSPZZZS", value: "危险品经营资质证书" },
    { key: "TZSBZZ", value: "特种设备制造许可证" },
    { key: "TZSJXKZ", value: "特种设备设计许可证" },
    { key: "TZSBAQGZWX", value: "特种设备安装改造维修许可证" },
    { key: "AQSC", value: "安全生产许可证" },
    { key: "WXHXJY", value: "危险化学品经营许可证" },
    { key: "WXHXSY", value: "危险化学品使用许可证" },
    { key: "ZDXHPJY", value: "非药品类易制毒化学品经营备案证明" },
    { key: "FBHGZ", value: "防爆合格证" },
    { key: "QGGYPSC", value: "全国工业产品生产许可证" },
    { key: "DLYSJY", value: "道路运输经营许可证" },
    { key: "ZZJLQJ", value: "制造计量器具许可证" },
    { key: "ZGQZXCP", value: "中国国家强制性产品认证证书" },
    { key: "FSAQ", value: "辐射安全许可证" },
    { key: "YJBZYP", value: "冶金标准样品认可证" },
    { key: "QPCZ", value: "气瓶充装许可证" },
    { key: "SPPF", value: "食品批发（流通、卫生）许可证" },
    { key: "MYHCYSBSJZG", value: "民用核承压设备设计资格许可证" },
    { key: "MYHCYSBZZZG", value: "民用核承压设备制造资格许可证" },
    { key: "MYAQSBZZ", value: "民用核安全设备制造许可证" },
    { key: "MYAQSBSJ", value: "民用核安全设备设计许可证" },
    { key: "FLGCZYSJZZ", value: "防雷工程专业设计资质证书" },
    { key: "FLGCZYSGZZ", value: "防雷工程专业施工资质证书" },
    { key: "YSJY", value: "印刷经营许可" },
    { key: "CPPFJY", value: "成品油批发经营许可" },
    { key: "QTLX", value: "其他类型证书" }
]